spring.datasource.url=jdbc:mysql://localhost:3306/placement_portal
spring.datasource.username=root
spring.datasource.password=Expecto@12@3

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080

jwt.secret=357638792F423F4428472B4B6250655368566D597133743677397A2443264629
jwt.expiration=36000000
jwt.refresh-expiration=604800000

app.admin.invitation-key=ADMIN@PLACEMENT2026
app.company.invitation-key=COMPANY@PLACEMENT2026

cloudinary.cloud-name=hz3fotxp
cloudinary.api-key=844568614766243
cloudinary.api-secret=-OB4U6Q5D5Mrtf8epOvuSaD_DUw

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB